package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

const httpTemplate = `// Code generated by protoc-gen-httpx. DO NOT EDIT.
// source: {{.SourceFile}}

package {{.Package}}

import (
	"context"

	"github.com/plsenp/httpx"
	"github.com/plsenp/httpx/stringx"
	httpxerrors "github.com/plsenp/httpx/errors"
)

{{range .Services}}
{{$serviceName := .Name}}
// {{$serviceName}}HTTPServer is the HTTP server interface for {{$serviceName}}
type {{$serviceName}}HTTPServer interface {
{{range .Methods}}
	{{.Name}}(context.Context, *{{.RequestType}}) (*{{.ResponseType}}, error)
{{end}}
}

// Register{{$serviceName}}Routes registers all HTTP routes for {{$serviceName}}
func Register{{$serviceName}}Routes(router *httpx.Router, service {{$serviceName}}HTTPServer) {
{{range .Methods}}
	// {{.Name}}: {{.Method}} {{.Path}}
	router.{{.Method}}("{{.Path}}", func(c *httpx.Ctx) error {
		req := &{{.RequestType}}{}
		{{if .HasBody}}
		// Bind body
		if err := c.BindJSON(req); err != nil {
			return httpxerrors.NewBindError("invalid request body", err)
		}
		{{else}}
		// Bind query parameters
		{{range .QueryParams}}
		if val := c.Query("{{.ProtoName}}"); val != "" {
			{{.Name}}, err := stringx.To[{{.Type}}](val)
			if err != nil {
				return httpxerrors.NewBindError("invalid query parameter: {{.ProtoName}}", err)
			}
			req.{{.Name}} = {{.Name}}
		}
		{{end}}
		{{end}}
		// Bind path parameters
		{{range .PathParams}}
		{{.Name}}, err := stringx.To[{{.Type}}](c.Param("{{.ProtoName}}"))
		if err != nil {
			return httpxerrors.NewBindError("invalid path parameter: {{.ProtoName}}", err)
		}
		req.{{.Name}} = {{.Name}}
		{{end}}
		resp, err := service.{{.Name}}(c.Request().Context(), req)
		if err != nil {
			return err
		}
		return c.Render(200, resp)
	})
{{end}}
}
{{end}}
`

// PathParam represents a path parameter
type PathParam struct {
	Name      string
	ProtoName string
	Type      string
}

// QueryParam represents a query parameter
type QueryParam struct {
	Name      string
	ProtoName string
	Type      string
}

// MethodInfo represents a method with HTTP binding
type MethodInfo struct {
	Name         string
	Method       string
	Path         string
	RequestType  string
	ResponseType string
	HasBody      bool
	PathParams   []PathParam
	QueryParams  []QueryParam
}

// ServiceInfo represents a service with HTTP methods
type ServiceInfo struct {
	Name    string
	Methods []MethodInfo
}

// TemplateData represents the data for code generation
type TemplateData struct {
	SourceFile string
	Package    string
	Services   []ServiceInfo
}

func main() {
	var flags flag.FlagSet
	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_httpx.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	data := TemplateData{
		SourceFile: file.Desc.Path(),
		Package:    string(file.GoPackageName),
	}

	for _, service := range file.Services {
		svcInfo := ServiceInfo{
			Name: string(service.Desc.Name()),
		}

		for _, method := range service.Methods {
			httpRule := extractHTTPRule(method)
			if httpRule == nil {
				continue
			}

			pathParams := extractPathParams(httpRule.Path, method.Input)
			queryParams := extractQueryParams(pathParams, httpRule.Body, method.Input)

			methodInfo := MethodInfo{
				Name:         string(method.Desc.Name()),
				Method:       httpRule.Method,
				Path:         httpRule.Path,
				RequestType:  method.Input.GoIdent.GoName,
				ResponseType: method.Output.GoIdent.GoName,
				HasBody:      httpRule.Body != "",
				PathParams:   pathParams,
				QueryParams:  queryParams,
			}
			svcInfo.Methods = append(svcInfo.Methods, methodInfo)
		}

		if len(svcInfo.Methods) > 0 {
			data.Services = append(data.Services, svcInfo)
		}
	}

	if len(data.Services) == 0 {
		return nil
	}

	tmpl, err := template.New("httpx").Parse(httpTemplate)
	if err != nil {
		gen.Error(fmt.Errorf("failed to parse template: %v", err))
		return nil
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		gen.Error(fmt.Errorf("failed to execute template: %v", err))
		return nil
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		g.P(buf.String())
		gen.Error(fmt.Errorf("failed to format code: %v", err))
		return g
	}

	g.P(string(formatted))
	return g
}

// HTTPRule represents extracted HTTP rule
type HTTPRule struct {
	Method string
	Path   string
	Body   string
}

func extractHTTPRule(method *protogen.Method) *HTTPRule {
	if method.Desc.Options() == nil {
		return nil
	}

	ext := proto.GetExtension(method.Desc.Options(), annotations.E_Http)
	httpRule, ok := ext.(*annotations.HttpRule)
	if !ok || httpRule == nil {
		return nil
	}

	rule := &HTTPRule{
		Body: httpRule.Body,
	}

	switch pattern := httpRule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		rule.Method = "Get"
		rule.Path = pattern.Get
	case *annotations.HttpRule_Post:
		rule.Method = "Post"
		rule.Path = pattern.Post
	case *annotations.HttpRule_Put:
		rule.Method = "Put"
		rule.Path = pattern.Put
	case *annotations.HttpRule_Delete:
		rule.Method = "Delete"
		rule.Path = pattern.Delete
	case *annotations.HttpRule_Patch:
		rule.Method = "Patch"
		rule.Path = pattern.Patch
	default:
		return nil
	}

	return rule
}

// extractPathParams extracts path parameters from URL pattern
func extractPathParams(path string, msg *protogen.Message) []PathParam {
	var params []PathParam
	// Extract {param} from path like "/users/{id}"
	parts := strings.Split(path, "/")
	for _, part := range parts {
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			paramName := strings.TrimSuffix(strings.TrimPrefix(part, "{"), "}")
			// Find field in message
			for _, field := range msg.Fields {
				if string(field.Desc.Name()) == paramName {
					params = append(params, PathParam{
						Name:      field.GoName, // Use GoName for correct field name
						ProtoName: paramName,
						Type:      getGoType(field),
					})
					break
				}
			}
		}
	}
	return params
}

// extractQueryParams extracts query parameters (fields not in path and not in body)
func extractQueryParams(pathParams []PathParam, body string, msg *protogen.Message) []QueryParam {
	var params []QueryParam
	pathParamMap := make(map[string]bool)
	for _, p := range pathParams {
		pathParamMap[p.ProtoName] = true // Use ProtoName for matching
	}

	for _, field := range msg.Fields {
		fieldName := string(field.Desc.Name())
		// Skip path params
		if pathParamMap[fieldName] {
			continue
		}
		// Skip body fields if body is "*"
		if body == "*" {
			continue
		}
		// Skip specific body field
		if body == fieldName {
			continue
		}

		params = append(params, QueryParam{
			Name:      field.GoName, // Use GoName for correct field name
			ProtoName: fieldName,
			Type:      getGoType(field),
		})
	}
	return params
}

// getGoType returns Go type name for protobuf field
func getGoType(field *protogen.Field) string {
	switch field.Desc.Kind().String() {
	case "int32":
		return "int32"
	case "int64":
		return "int64"
	case "string":
		return "string"
	case "bool":
		return "bool"
	default:
		return "string"
	}
}
