// Code generated by protoc-gen-httpx. DO NOT EDIT.
// source: user.proto

package testdata

import (
	"context"

	"github.com/plsenp/httpx"
	"github.com/plsenp/httpx/convert"
	httpxerrors "github.com/plsenp/httpx/errors"
)

// UserServiceHTTPServer is the HTTP server interface for UserService
type UserServiceHTTPServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)

	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)

	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)

	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)

	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

// RegisterUserServiceRoutes registers all HTTP routes for UserService
func RegisterUserServiceRoutes(engine *httpx.Engine, service UserServiceHTTPServer) {

	// GetUser: Get /users/{id}
	engine.Router().Get("/users/{id}", func(c *httpx.Context) error {
		req := &GetUserRequest{}

		// Bind path parameter: Id
		Id, err := convert.Convert[int64](c.Param("id"))
		if err != nil {
			return httpxerrors.NewBindError("invalid path parameter: id", err)
		}
		req.Id = Id

		// Bind query parameters

		resp, err := service.GetUser(c.Request().Context(), req)
		if err != nil {
			return err
		}
		return c.Render(200, resp)
	})

	// ListUsers: Get /users
	engine.Router().Get("/users", func(c *httpx.Context) error {
		req := &ListUsersRequest{}

		// Bind query parameters

		if val := c.Query("page"); val != "" {
			Page, err := convert.Convert[int32](val)
			if err != nil {
				return httpxerrors.NewBindError("invalid query parameter: page", err)
			}
			req.Page = Page
		}

		if val := c.Query("limit"); val != "" {
			Limit, err := convert.Convert[int32](val)
			if err != nil {
				return httpxerrors.NewBindError("invalid query parameter: limit", err)
			}
			req.Limit = Limit
		}

		resp, err := service.ListUsers(c.Request().Context(), req)
		if err != nil {
			return err
		}
		return c.Render(200, resp)
	})

	// CreateUser: Post /users
	engine.Router().Post("/users", func(c *httpx.Context) error {
		req := &CreateUserRequest{}

		// Bind body
		if err := c.Bind(req); err != nil {
			return httpxerrors.NewBindError("invalid request body", err)
		}

		resp, err := service.CreateUser(c.Request().Context(), req)
		if err != nil {
			return err
		}
		return c.Render(200, resp)
	})

	// UpdateUser: Put /users/{id}
	engine.Router().Put("/users/{id}", func(c *httpx.Context) error {
		req := &UpdateUserRequest{}

		// Bind path parameter: Id
		Id, err := convert.Convert[int64](c.Param("id"))
		if err != nil {
			return httpxerrors.NewBindError("invalid path parameter: id", err)
		}
		req.Id = Id

		// Bind body
		if err := c.Bind(req); err != nil {
			return httpxerrors.NewBindError("invalid request body", err)
		}

		resp, err := service.UpdateUser(c.Request().Context(), req)
		if err != nil {
			return err
		}
		return c.Render(200, resp)
	})

	// DeleteUser: Delete /users/{id}
	engine.Router().Delete("/users/{id}", func(c *httpx.Context) error {
		req := &DeleteUserRequest{}

		// Bind path parameter: Id
		Id, err := convert.Convert[int64](c.Param("id"))
		if err != nil {
			return httpxerrors.NewBindError("invalid path parameter: id", err)
		}
		req.Id = Id

		// Bind query parameters

		resp, err := service.DeleteUser(c.Request().Context(), req)
		if err != nil {
			return err
		}
		return c.Render(200, resp)
	})

}
